### ISSUE TITLE
Sharp corner with GtkStack in titlebar

### ISSUE THREAD

**Issue by johnfactotum** [jnsh/arc-theme#56]
This can be seen in Epiphany:

![image](https://user-images.githubusercontent.com/50942278/85939358-42350480-b904-11ea-953b-05651b49d7e4.png)

Notice the top right corner is not round. When clicking on the "Tabs" button (the last button in the action bar), the right corner will be rounded, but the left will now be square.

Adwaita, for comparison:

![image](https://user-images.githubusercontent.com/50942278/85939368-5bd64c00-b904-11ea-91fb-45d8d4531006.png)

I think this happens when a GtkStack is used to house many headerbars. Also happens in Foliate 2.3.0.

**Comment by jnsh** [comment]
Thank you for the report. Looks like this issue has been reported to [libhandy](https://gitlab.gnome.org/GNOME/libhandy/-/issues/21) and [GTK](https://gitlab.gnome.org/GNOME/gtk/-/issues/1264), and has been fixed for Adwaita with https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/322.

Most likely it should be possible to port the Adwaita fix for Arc. I'll have a look at some point.

**Comment by johnfactotum** [comment]
It's not exactly the same issue. The situation for HdyLeaflet is more complicated because of the sliding animations and split headerbars. In this case, it's just a stack, showing only one child at a time.

In Adwaita I think they've had this for a long time now:
```scss
headerbar { // headerbar border rounding

  // ...

  window stack & { // tackles the stacked headerbars case
    &:first-child, &:last-child {
      &:backdrop, & {
        border-top-left-radius: 7px;
        border-top-right-radius: 7px;
      }
    }
  }

 // ...

}
```
https://gitlab.gnome.org/GNOME/gtk/-/blob/badbde5041382695122107bd7b48230fb58e9b83/gtk/theme/Adwaita/_common.scss#L1833
